-- MySQL Script generated by MySQL Workbench
-- Fri Feb 19 12:59:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema platz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema platz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `platz` DEFAULT CHARACTER SET utf8 ;
USE `platz` ;

-- -----------------------------------------------------
-- Table `platz`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platz`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `icone` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platz`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platz`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platz`.`ressources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platz`.`ressources` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `description` VARCHAR(255) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `fichier` VARCHAR(45) NOT NULL,
  `categorie_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_ressources_categories_idx` (`categorie_id` ASC),
  INDEX `fk_ressources_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ressources_categories`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `platz`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ressources_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `platz`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platz`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platz`.`commentaires` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `ressource_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commentaires_users1_idx` (`user_id` ASC),
  INDEX `fk_commentaires_ressources1_idx` (`ressource_id` ASC),
  CONSTRAINT `fk_commentaires_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `platz`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaires_ressources1`
    FOREIGN KEY (`ressource_id`)
    REFERENCES `platz`.`ressources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
